spring:
  application:
    name: gameapi

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    driverClassName: oracle.jdbc.OracleDriver
    username: rm551528
    password: 090205

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  flyway:
    enabled: true
    clean-on-validation-error: true
    clean-disabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operationsSorter: alpha
    tagsSorter: alpha

jwt:
  secret: "change-me-in-prod-32-chars-minimum-secret-key-123456"
  expiration: 3600000

