-- Generated to match entity fields (H2/Postgres compatible)

CREATE TABLE IF NOT EXISTS game (
    id_game INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    editora VARCHAR(255),
    genero VARCHAR(100),
    ano_lancamento INT
);

CREATE TABLE IF NOT EXISTS player (
    id_player INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    idade INT,
    fav_game INT,
    CONSTRAINT fk_player_game FOREIGN KEY (fav_game) REFERENCES game(id_game)
);
